name: Publicar no NPM

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Permissão OBRIGATÓRIA para o Trusted Publishing

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          # REMOVI o registry-url daqui para ele não criar configuração com senha errada

      # [O PULO DO GATO] Criamos a config manualmente apenas apontando o local, sem pedir senha
      - run: echo "registry=https://registry.npmjs.org/" > .npmrc

      - run: npm ci
      - run: npm run build

      # O comando --provenance usa a identidade do GitHub (id-token) para logar
      - run: npm publish --provenance --access public
